let userModel,encryptPassword,sendErrorResponse,sendSuccessResponse;_f82‍.x([["createUserHandler",()=>createUserHandler],["updateHandler",()=>updateHandler],["deleteHandler",()=>deleteHandler],["getAllUsers",()=>getAllUsers]]);_f82‍.w("../schemas/User",[["userModel",["userModel"],function(v){userModel=v}]]);_f82‍.w("../utils/bcrypt",[["encryptPassword",["encryptPassword"],function(v){encryptPassword=v}]]);_f82‍.w("../utils/response",[["sendErrorResponse",["sendErrorResponse"],function(v){sendErrorResponse=v}],["sendSuccessResponse",["sendSuccessResponse"],function(v){sendSuccessResponse=v}]]);



       const createUserHandler = async (req, res) => {
  try {
    const { email, password } = req.body;
    if (email === undefined || password === undefined) {
      throw new Error("Arguments Missing");
    }
    const hashPassword = await encryptPassword(password);
    const user = await userModel.create({
      email,
      password: hashPassword,
    });
    sendSuccessResponse(res, user);
  } catch (error) {
    _f82‍.g.console.log(error);
    sendSuccessResponse(res, error.message);
  }
};

       const updateHandler = async (req, res) => {
  try {
    const { oldEmail, newEmail, password } = req.body;
    if (
      oldEmail === undefined ||
      newEmail === undefined ||
      password === undefined
    ) {
      throw new Error("Arguments Missing");
    }
    const user = await userModel.findOne({ email: oldEmail });
    if (user === null) throw new Error("User Not Found");

    user.email = newEmail;
    const hashPassword = await encryptPassword(password);
    user.password = hashPassword;
    await user.save();
    sendSuccessResponse(res, user);
  } catch (error) {
    _f82‍.g.console.log(error.message);
    sendErrorResponse(res, error.message);
  }
};

       const deleteHandler = async (req, res) => {
  try {
    const { email } = req.body;
    if (email === undefined) {
      throw new Error("Arguments Missing");
    }
    const user = await userModel.findOne({ email });
    if (user === null) throw new Error("User Not Found");
    await user.remove();
    sendSuccessResponse(res, "Successfully Removed");
  } catch (error) {
    sendErrorResponse(res, error.message);
  }
};

       const getAllUsers = async (req, res) => {
  try {
    const users = await userModel.find();
    sendSuccessResponse(res, users);
  } catch (error) {
    sendErrorResponse(res, error.message);
  }
};
